### ISSUE TITLE
readTemperature incoherent with calculateTemp

### ISSUE THREAD

**Issue by gratefulfrog** [ArticCynda/AEM#2]
The computation of the temperature should be done in `calculateTemp`, i.e. the code 
```
 return BASE_TEMP + ((t * TEMP_REF / TOTAL_STEPS)- TEMP_BASE_VOLTAGE) * TEMP_RICO;
```

should be in `calculateTemp` and called at the return of `readTemperature`

**Comment by ArticCynda** [comment]
Added conditional to switch between dedicated temperature reading with `readTemperature`, and temperature acquisition by sequencer.
