### ISSUE TITLE
setting bits to LOW

### ISSUE THREAD

**Issue by gratefulfrog** [ArticCynda/AEM#3]
The "normal" way of setting a single bit low is to AND the bitwise not of the bit to be set to Zero

example if `XX= 0B111`, and we want to set the 2nd bit to zero, 
```
XX &= ~0b010
  0B111
& 0B101
---------
  0B101
```

in file yspi.cpp:
Line 40: PORTD = (PORTD | _BV(PORTD4)) ^ _BV(PORTD4);
could be improved to:  PORTD &= ~ _BV(PORTD4);

in file: ad7689.cpp
Line 304: PORTD = (PORTD | _BV(PORTD4)) ^ _BV(PORTD4);
could be improved to :PORTD =& ~_BV(PORTD4);
Line 318: PORTD = (PORTD | _BV(PORTD4)) ^ _BV(PORTD4);
could be improved to: PORTD &= ~ _BV(PORTD4);

**Comment by ArticCynda** [comment]
Thanks for the suggestion, this has now been fixed!
