### ISSUE TITLE
Baud rate register setting in yspi

### ISSUE THREAD

**Issue by gratefulfrog** [ArticCynda/AEM#5]
in the flile yspi.cpp

setting the baud rate register is incorrect!
line 122: `UBRR1 = 3;`

This value is defined in table 23-1 of the [2650 data sheet](http://www.atmel.com/Images/Atmel-2549-8-bit-AVR-Microcontroller-ATmega640-1280-1281-2560-2561_datasheet.pdf).

This absolutely must be fixed!

Also, I think that we should use the following code, rather than the stuff that we "adapted" from NG's code!

The proper initialization code is:
```
void USART_Init( unsigned int baud ){
  UBRRn = 0;
  /* Setting the XCKn port pin as output, enables master mode. */
  XCKn_DDR |= (1<<XCKn);
  /* Set MSPI mode of operation and SPI data mode 0. */
  UCSRnC = (1<<UMSELn1)|(1<<UMSELn0)|(0<<UCPHAn)|(0<<UCPOLn);
  /* Enable receiver and transmitter. */
  UCSRnB = (1<<RXENn)|(1<<TXENn);
  /* Set baud rate. */
  /* IMPORTANT: The Baud Rate must be set after the transmitter is enabled */
  UBRRn = baud;
}
```

proper receive/send code:
```
unsigned char USART_Receive( void ){
  /* Wait for empty transmit buffer */
  while ( !( UCSRnA & (1<<UDREn)) );
  /* Put data into buffer, sends the data */
  UDRn = data;
  /* Wait for data to be received */
  while( !(UCSRnA & (1<<RXCn)) );
  /* Get and return received data from buffer */
  return UDRn;
}
```

Moral of the story: read the data sheet until it makes sense!!!

**Comment by ArticCynda** [comment]
All baud rate configurations suggested in the datasheet have been tried, according to the values specified for UBRR in table 22-12 for 16 MHz on p. 226 of the datasheet. No change in behavior could be observed.

The alternate code for sending and receiving suggested below also does not work.

**Comment by ArticCynda** [comment]
UBRR = 1 sets the baud rate close to maximum, regardless of the value of U2Xn, so this seems a safe value.

**Comment by ArticCynda** [comment]
From https://feilipu.me/2015/02/17/avr-atmega-usart-spi-mspim/
"High Resolution Baud Rate Generator – yes, it is. The MSPIM baud rate can be set to any rate up to half the FCPU clock rate. Whilst there may be little need to run the MSPIM interface at less than the maximum for pure SPI transactions, it is possible to to use this feature, together with double buffered transmission, to generate continuous arbitrary binary bit-streams at almost any rate."

With the formula baudRate = FCPU / (2 * UBRRn + 1), half the FCPU speed is configured by UBRRn = 0.
